import React, { useState, useRef, useEffect } from 'react';
import { FileText, Send, BookOpen, Shield, RefreshCw, MessageCircle, ChevronDown, ChevronRight } from 'lucide-react';
import { api } from '../../services/api';

// ─── Policy sections rendered directly (sourced from the PDF handbook) ──────

const SECTIONS = [
  {
    id: 'membership',
    icon: '💳',
    title: 'Membership & Plans',
    content: [
      'HealthyLife offers three plans: **Basic** (free), **Pro** ($19.99/month), and **Elite** ($39.99/month).',
      'Annual plans receive a **20% discount** compared to monthly billing.',
      'Plans auto-renew unless cancelled at least 24 hours before the renewal date.',
      'Members can upgrade or downgrade plans at any time; changes take effect at the next billing cycle.',
    ],
  },
  {
    id: 'refunds',
    icon: '💰',
    title: 'Refund Policy',
    content: [
      '**Monthly plans**: No refunds after the billing date. Cancellation stops future charges.',
      '**Annual plans**: Full refund within **14 days** of purchase if no coaching sessions have been used.',
      'After 14 days, annual plans receive a pro-rated refund minus a 10% processing fee.',
      'Coaching session packages (5-session or 10-session bundles) are **non-refundable** once any session is used.',
      'Refund requests must be submitted through Settings → Billing → Request Refund.',
    ],
  },
  {
    id: 'coaching',
    icon: '🏋️',
    title: 'Coaching Sessions',
    content: [
      'Elite plan members receive **2 coaching sessions per month**; Pro members receive **1 per month**.',
      'Sessions must be booked at least **24 hours in advance** through the app.',
      'Cancellations with less than 12 hours notice forfeit the session.',
      'Cancellations with more than 12 hours notice are rescheduled at no charge.',
      'If a coach cancels, the session is automatically rescheduled or a credit is issued.',
      'All HealthyLife coaches hold at least one accredited certification (NASM, ACE, CSCS, RD, or equivalent).',
    ],
  },
  {
    id: 'privacy',
    icon: '🔒',
    title: 'Data & Privacy',
    content: [
      'HealthyLife collects health data solely to provide **personalised features**.',
      'Data is stored encrypted at rest (AES-256) and in transit (TLS 1.3).',
      '**Health data is never sold to third parties.**',
      'AI features use anonymised, aggregated data; individual data requires explicit opt-in consent.',
      'Members can export or delete all their data from Settings → Privacy → Manage Data.',
      'Data deletion requests are processed within **30 days**.',
    ],
  },
  {
    id: 'ai',
    icon: '🤖',
    title: 'AI Assistant Policy',
    content: [
      'The AI Health Advisor provides **general wellness guidance only** — not medical advice.',
      'AI-generated meal and workout plans are suggestions; consult a healthcare professional before major health changes.',
      'AI responses are generated by third-party language models (Groq/Gemini). HealthyLife is not liable for inaccurate AI outputs.',
    ],
  },
  {
    id: 'conduct',
    icon: '🤝',
    title: 'Code of Conduct',
    content: [
      'Members must treat coaches and other users **respectfully** in the chat feature.',
      'Harassment, hate speech, or sharing another user\'s personal information will result in **immediate account termination without refund**.',
      'Coaches must maintain professional boundaries and adhere to their certification body\'s code of ethics.',
    ],
  },
  {
    id: 'termination',
    icon: '⚠️',
    title: 'Account Termination',
    content: [
      'HealthyLife reserves the right to terminate accounts for violations of the Code of Conduct, fraudulent activity, or chargebacks.',
      'Terminated accounts are not eligible for refunds.',
      'Members may voluntarily close their account from Settings → Account → Close Account.',
    ],
  },
  {
    id: 'contact',
    icon: '📞',
    title: 'Contact & Support',
    content: [
      'Support is available via in-app chat **Monday–Friday, 9 AM–6 PM GMT+6**.',
      'For billing disputes, email **billing@healthylife.app** within 60 days of the charge.',
      'For data privacy requests, email **privacy@healthylife.app**.',
    ],
  },
];

// ─── Inline chatbot ───────────────────────────────────────────────────────────

interface Msg { from: 'bot' | 'user'; text: string; error?: boolean; }

const GREETING: Msg = {
  from: 'bot',
  text: 'Hi! Ask me anything about HealthyLife policies — refunds, bookings, data privacy, and more.',
};

const SUGGESTIONS = [
  'Can I get a refund on my annual plan?',
  'What happens if I miss a coaching session?',
  'How is my health data protected?',
  'What certifications do coaches need?',
];

const PolicyChat: React.FC = () => {
  const [messages, setMessages] = useState<Msg[]>([GREETING]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const listRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    listRef.current?.scrollTo({ top: listRef.current.scrollHeight, behavior: 'smooth' });
  }, [messages, loading]);

  const ask = async (question: string) => {
    const q = question.trim();
    if (!q || loading) return;
    setMessages(m => [...m, { from: 'user', text: q }]);
    setInput('');
    setLoading(true);
    try {
      const { answer } = await api.askPolicy(q);
      setMessages(m => [...m, { from: 'bot', text: answer }]);
    } catch (err) {
      const text = err instanceof Error ? err.message : 'Something went wrong.';
      setMessages(m => [...m, { from: 'bot', text, error: true }]);
    } finally {
      setLoading(false);
      inputRef.current?.focus();
    }
  };

  return (
    <div
      className="flex flex-col rounded-2xl overflow-hidden"
      style={{
        height: 480,
        background: 'var(--hl-surface)',
        border: '1px solid var(--hl-border)',
        boxShadow: 'var(--hl-shadow-xl)',
      }}
    >
      {/* Header */}
      <div className="flex items-center gap-3 px-4 py-3 text-white" style={{ background: 'var(--hl-gradient-hero)' }}>
        <div className="w-9 h-9 rounded-xl flex items-center justify-center shrink-0" style={{ background: 'rgba(255,255,255,.2)' }}>
          <MessageCircle className="w-5 h-5" />
        </div>
        <div>
          <p className="text-sm font-bold leading-tight">Policy Assistant</p>
          <p className="text-[11px] text-white/80">Powered by the HealthyLife Policy Handbook</p>
        </div>
      </div>

      {/* Messages */}
      <div ref={listRef} className="flex-1 overflow-y-auto px-4 py-4 space-y-3">
        {messages.map((m, i) => (
          <div key={i} className={`flex ${m.from === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div
              className="max-w-[85%] px-3.5 py-2.5 rounded-2xl text-[13px] leading-relaxed whitespace-pre-line"
              style={
                m.from === 'user'
                  ? { background: 'var(--hl-green)', color: '#fff', borderBottomRightRadius: 4 }
                  : {
                      background: m.error ? '#FDECEC' : 'var(--hl-surface-alt)',
                      color: m.error ? '#9B2C2C' : 'var(--hl-text-primary)',
                      border: '1px solid var(--hl-border-light)',
                      borderBottomLeftRadius: 4,
                    }
              }
            >
              {m.text}
            </div>
          </div>
        ))}

        {messages.length === 1 && (
          <div className="flex flex-wrap gap-2 pt-1">
            {SUGGESTIONS.map(s => (
              <button
                key={s}
                onClick={() => ask(s)}
                className="text-xs font-semibold px-3 py-1.5 rounded-xl text-left transition-colors hover:brightness-95"
                style={{ background: 'var(--hl-green-light)', color: 'var(--hl-green)', border: '1px solid var(--hl-border-light)' }}
              >
                {s}
              </button>
            ))}
          </div>
        )}

        {loading && (
          <div className="flex items-center gap-1.5 px-3.5 py-3 rounded-2xl w-fit" style={{ background: 'var(--hl-surface-alt)' }}>
            {[0, 1, 2].map(i => (
              <span
                key={i}
                className="w-2 h-2 rounded-full inline-block"
                style={{
                  background: 'var(--hl-green)',
                  animation: 'pulse 1.2s ease-in-out infinite',
                  animationDelay: `${i * 0.2}s`,
                }}
              />
            ))}
          </div>
        )}
      </div>

      {/* Input */}
      <form
        onSubmit={e => { e.preventDefault(); ask(input); }}
        className="flex items-center gap-2 p-3"
        style={{ borderTop: '1px solid var(--hl-border-light)' }}
      >
        <input
          ref={inputRef}
          value={input}
          onChange={e => setInput(e.target.value)}
          maxLength={500}
          placeholder="Ask about refunds, bookings, privacy…"
          className="flex-1 min-w-0 px-3.5 py-2.5 rounded-xl text-sm outline-none"
          style={{ background: 'var(--hl-surface-alt)', border: '1px solid var(--hl-border)', color: 'var(--hl-text-primary)' }}
        />
        <button
          type="submit"
          disabled={loading || !input.trim()}
          className="w-10 h-10 flex items-center justify-center rounded-xl text-white disabled:opacity-40 transition"
          style={{ background: 'var(--hl-green)' }}
        >
          <Send className="w-4 h-4" />
        </button>
      </form>
    </div>
  );
};

// ─── Render bold text inside policy bullets ──────────────────────────────────

const RenderBullet: React.FC<{ text: string }> = ({ text }) => {
  const parts = text.split(/\*\*(.+?)\*\*/g);
  return (
    <span>
      {parts.map((p, i) =>
        i % 2 === 1 ? <strong key={i} className="font-semibold">{p}</strong> : <span key={i}>{p}</span>
      )}
    </span>
  );
};

// ─── Accordion section ───────────────────────────────────────────────────────

const PolicySection: React.FC<{ section: typeof SECTIONS[0]; defaultOpen?: boolean }> = ({ section, defaultOpen }) => {
  const [open, setOpen] = useState(defaultOpen ?? false);
  return (
    <div
      className="rounded-2xl overflow-hidden transition-all"
      style={{ border: '1px solid var(--hl-border)', background: 'var(--hl-surface)' }}
    >
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-5 py-4 text-left transition-colors hover:brightness-95"
        style={{ background: open ? 'var(--hl-surface-alt)' : 'var(--hl-surface)' }}
      >
        <div className="flex items-center gap-3">
          <span className="text-xl">{section.icon}</span>
          <span className="font-semibold text-base" style={{ color: 'var(--hl-text-primary)' }}>{section.title}</span>
        </div>
        {open ? (
          <ChevronDown className="w-4 h-4 shrink-0" style={{ color: 'var(--hl-green)' }} />
        ) : (
          <ChevronRight className="w-4 h-4 shrink-0" style={{ color: 'var(--hl-text-tertiary)' }} />
        )}
      </button>
      {open && (
        <ul className="px-5 py-4 space-y-2.5" style={{ borderTop: '1px solid var(--hl-border-light)' }}>
          {section.content.map((line, i) => (
            <li key={i} className="flex items-start gap-2.5 text-sm" style={{ color: 'var(--hl-text-secondary)' }}>
              <span className="mt-1.5 w-1.5 h-1.5 rounded-full shrink-0" style={{ background: 'var(--hl-green)' }} />
              <RenderBullet text={line} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

// ─── Main PolicyView ─────────────────────────────────────────────────────────

export const PolicyView: React.FC = () => {
  const pdfUrl = '/api/policy/pdf';

  return (
    <div className="min-h-screen py-10 px-4 sm:px-6 lg:px-8" style={{ background: 'var(--hl-bg)' }}>
      <div className="max-w-6xl mx-auto space-y-10">

        {/* Hero */}
        <div className="text-center space-y-3">
          <div
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full text-sm font-semibold text-white"
            style={{ background: 'var(--hl-gradient-hero)' }}
          >
            <Shield className="w-4 h-4" />
            Official Policy Handbook
          </div>
          <h1 className="text-4xl font-extrabold" style={{ color: 'var(--hl-text-primary)' }}>
            HealthyLife Policies
          </h1>
          <p className="text-lg max-w-2xl mx-auto" style={{ color: 'var(--hl-text-secondary)' }}>
            Everything you need to know about your membership, refunds, coaching sessions, data privacy, and more.
          </p>
          <a
            href="data:application/pdf;base64,"
            download="healthylife_policy_handbook.pdf"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white transition hover:opacity-90"
            style={{ background: 'var(--hl-green)' }}
            onClick={e => {
              // Serve via the backend route
              e.preventDefault();
              window.open('/api/policy/pdf', '_blank');
            }}
          >
            <FileText className="w-4 h-4" />
            Download PDF Handbook
          </a>
        </div>

        {/* Two-column layout */}
        <div className="grid lg:grid-cols-5 gap-8">

          {/* Left: accordion sections (3/5 width) */}
          <div className="lg:col-span-3 space-y-3">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2" style={{ color: 'var(--hl-text-primary)' }}>
              <BookOpen className="w-5 h-5" style={{ color: 'var(--hl-green)' }} />
              Policy Sections
            </h2>
            {SECTIONS.map((s, i) => (
              <PolicySection key={s.id} section={s} defaultOpen={i === 0} />
            ))}
          </div>

          {/* Right: chatbot (2/5 width) */}
          <div className="lg:col-span-2">
            <h2 className="text-lg font-bold mb-4 flex items-center gap-2" style={{ color: 'var(--hl-text-primary)' }}>
              <MessageCircle className="w-5 h-5" style={{ color: 'var(--hl-green)' }} />
              Ask the Policy Bot
            </h2>
            <PolicyChat />
            <p className="mt-2 text-xs text-center" style={{ color: 'var(--hl-text-tertiary)' }}>
              AI answers are based on the Policy Handbook. For disputes, contact support directly.
            </p>
          </div>
        </div>

        {/* PDF iframe embed */}
        <div className="rounded-2xl overflow-hidden" style={{ border: '1px solid var(--hl-border)' }}>
          <div className="flex items-center justify-between px-5 py-3" style={{ background: 'var(--hl-surface-alt)', borderBottom: '1px solid var(--hl-border)' }}>
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4" style={{ color: 'var(--hl-green)' }} />
              <span className="font-semibold text-sm" style={{ color: 'var(--hl-text-primary)' }}>
                HealthyLife Policy Handbook (PDF)
              </span>
            </div>
            <a
              href="/api/policy/pdf"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5 rounded-lg transition hover:opacity-80"
              style={{ color: 'var(--hl-green)', background: 'var(--hl-green-light)' }}
            >
              <RefreshCw className="w-3 h-3" />
              Open in new tab
            </a>
          </div>
          <iframe
            src="/api/policy/pdf"
            title="HealthyLife Policy Handbook PDF"
            className="w-full"
            style={{ height: 700, border: 'none' }}
          />
        </div>
      </div>
    </div>
  );
};
